# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: container.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import svmp_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='container.proto',
  package='svmp',
  serialized_pb='\n\x0f\x63ontainer.proto\x12\x04svmp\x1a\nsvmp.proto\"\xe9\x01\n\tContainer\x12,\n\x05\x63type\x18\x01 \x02(\x0e\x32\x1d.svmp.Container.ContainerType\x12\x11\n\tproxyhost\x18\x02 \x01(\t\x12\x11\n\tproxyport\x18\x03 \x01(\x05\x12\x1e\n\x07request\x18\x04 \x01(\x0b\x32\r.svmp.Request\x12 \n\x08response\x18\x05 \x01(\x0b\x32\x0e.svmp.Response\"F\n\rContainerType\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\r\n\tCONNECTED\x10\x01\x12\x0b\n\x07REQUEST\x10\x02\x12\x0c\n\x08RESPONSE\x10\x03\x42\x02H\x03')



_CONTAINER_CONTAINERTYPE = _descriptor.EnumDescriptor(
  name='ContainerType',
  full_name='svmp.Container.ContainerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=201,
  serialized_end=271,
)


_CONTAINER = _descriptor.Descriptor(
  name='Container',
  full_name='svmp.Container',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ctype', full_name='svmp.Container.ctype', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proxyhost', full_name='svmp.Container.proxyhost', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proxyport', full_name='svmp.Container.proxyport', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request', full_name='svmp.Container.request', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='svmp.Container.response', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTAINER_CONTAINERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=271,
)

_CONTAINER.fields_by_name['ctype'].enum_type = _CONTAINER_CONTAINERTYPE
_CONTAINER.fields_by_name['request'].message_type = svmp_pb2._REQUEST
_CONTAINER.fields_by_name['response'].message_type = svmp_pb2._RESPONSE
_CONTAINER_CONTAINERTYPE.containing_type = _CONTAINER;
DESCRIPTOR.message_types_by_name['Container'] = _CONTAINER

class Container(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTAINER

  # @@protoc_insertion_point(class_scope:svmp.Container)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003')
# @@protoc_insertion_point(module_scope)
